version: '2.2'
services:
 dbserver:
  image: yobasystems/alpine-mariadb
  container_name: dbserver
  environment:
   MYSQL_ROOT_PASSWORD: toor
   MYSQL_USER: admin
   MYSQL_PASSWORD: nimda
  ports:
    - "3306:3306"
  volumes:
    - ./db_interview_test.sql:/docker-entrypoint-initdb.d/db_interview_test.sql
  restart: always

 # For golang apps services
 apps:
  image: golang:1.11.2-alpine
  container_name: apps
  ports:
   - "8095:8095"
  volumes:
   - ./apps:/go/src/apps
  working_dir: /go/src/apps
  environment:
   - GOBIN: /go/bin/
  command: >
    bash -c "go get -u github.com/golang/dep/cmd/dep
    && echo 'Success download dep, start dep ensure'
    && dep init
    && dep ensure
    && echo 'successfully downloaded dependency'
    && go run main.go"


volumes:
 dbdata:
  driver: local